club/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from club import views

urlpatterns = [
        url(r'^join_us/$', views.join_us,
        name='join_us'),
        url(r'^about_us/$',views.view_about_us,
        name='about_us'),
        url(r'^useful_videos/$', views.useful_videos, name = 'useful'),
        url(r'^gallery/$',views.gallery,
        name='gallery'),
        url(r'^contact_us$',views.contact_us,
        name='contact_us'),
        url(r'^member/(?P<member_id>\d+)/profile/$',views.member_profile,name='member_profile',),
]

qmisclub/urls.py
from django.conf.urls import *
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib import admin
from club import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^events/', include('events.urls')),
    url(r'^club/', include('club.urls')),
    url(r'^department/', include('department.urls')),
    url(r'^privacy_policy$', TemplateView.as_view(template_name='privacy_policy.html'), name = 'privacy_policy'),
    url(r'^term_of_use$', TemplateView.as_view(template_name='term_of_use.html'), name = 'term_of_use'),
    url(r'^college_guide/$',TemplateView.as_view(template_name='college_guide.html'),
    name='college_guide'),
    url(r'^FAQ$', views.FAQ,name='FAQ'),
    url(r'^$', views.index,name='index')

] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

club/models.py
from django.db import models
from django_resized import ResizedImageField
from django.core.urlresolvers import reverse
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.files.images import get_image_dimensions
import sys


class Category(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return u'{}'.format(self.name)

    class Meta:
        verbose_name_plural = "categories"


class Picture(models.Model):
    title = models.CharField(null=True, max_length=64, blank=True)
    image = models.ImageField(null=False)
    #image_width = models.IntegerField(null=False, default=300)
    #image_height = models.IntegerField(null=False, default=300)
    category = models.ForeignKey(
        Category, related_name="category_picture", null=True, blank=True)
    #home_page = models.BooleanField("show in home page", default=False)
    thumbnail = models.ImageField(null=True, blank=True)

    def __str__(self):
        return u'{}'.format(self.title)

    def save(self):
        if self.image:
            # Opening the uploaded image
            w, h = get_image_dimensions(self.image)
            aspect_ratio = float(w) / float(h)

            im = Image.open(self.image)
            im2 = Image.open(self.image)
            output = BytesIO()
            output2 = BytesIO()
            # Resize/modify the image
            if self.home_page:
                im = im.resize((1280, 720))
            else:
                im = im.resize((1280, int(1280 / aspect_ratio)))
            im2 = im.resize((400, 200))
            # after modifications, save it to the output
            im.save(output, format='JPEG', quality=70)
            im2.save(output2, format='JPEG', quality=50)
            output.seek(0)
            output2.seek(0)
            # change the imagefield value to be the newley modifed image value
            self.image = InMemoryUploadedFile(output, 'ImageField', "%s.jpg" % self.image.name.split(
                '.')[0], 'image/jpeg', sys.getsizeof(output), None)
            self.thumbnail = InMemoryUploadedFile(output2, 'ImageField', "%s.jpg" % self.image.name.split(
                '.')[0], 'image/jpeg', sys.getsizeof(output2), None)

        super(Picture, self).save()


class Member(models.Model):
    MAJORS = (("Management Information System", "Management Information System"),
              ("Operation & Supply Chain Managment",
               "Operation & Supply Chain Managment"),
              ("Marketing", "Marketing"),
              ("Economics", "Economics"),
              ("Management", "Management"),
              ("Accounting", "Accounting"),
              ("Public Administration", "Public Administration"),
              ("Finance", "Finance"))
    picture = models.ImageField(null=True, blank=True)
    name = models.CharField("Name", null=False, max_length=64)
    major = models.CharField(
        "Major", null=False, choices=sorted(MAJORS), max_length=64)
    skills = models.TextField("Skills", null=False)
    interests = models.TextField("Interests", null=False)
    position = models.CharField("Position", null=False, max_length=64)
    rank = models.IntegerField("Rank", null=False)

    def get_absolute_url(self):
        return reverse('member_profile', kwargs={'member_id': self.pk})

    def save(self):
        if self.picture:
            # Opening the uploaded image
            w, h = get_image_dimensions(self.picture)
            aspect_ratio = float(w) / float(h)
            im = Image.open(self.picture)

            output = BytesIO()

            # Resize/modify the image
            im = im.resize((1280, int(1280 / aspect_ratio)))

            # after modifications, save it to the output
            im.save(output, format='JPEG', quality=70)
            output.seek(0)

            # change the imagefield value to be the newley modifed image value
            self.picture = InMemoryUploadedFile(output, 'ImageField', "%s.jpg" % self.picture.name.split(
                '.')[0], 'image/jpeg', sys.getsizeof(output), None)

        super(Member, self).save()

    def __str__(self):
        return u'{}'.format(self.name)


class Video(models.Model):
    title = models.CharField(null=True, max_length=128, blank=True)
    video_id = models.CharField(max_length=500)
    category = models.ForeignKey(
        Category, related_name="category_video", null=True, blank=True)

    def __str__(self):
        return u'{}'.format(self.title)


class FAQ(models.Model):
    question = models.TextField(null=False, max_length=1000)
    answer = models.TextField(null=False, max_length=1000)


class WelcomingWord(models.Model):
    welcoming_word = models.TextField(null=False, max_length=2000)

    class Meta:
        verbose_name_plural = "Welcoming Word"


class HomePageVideo(models.Model):
    video_id = models.CharField(max_length=500)

    class Meta:
        verbose_name_plural = "Home Page Video"


class ContactUsVideo(models.Model):
    video_id = models.CharField(max_length=500)

    class Meta:
        verbose_name_plural = "Contact Us Video"

club/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .forms import *

"""def validate_file_extension(value):
    ''' validate file extention to only accept pdf files'''
    extentions=['.pdf', '.docx']
    if not value.name.endswith('.pdf') and not value.name.endswith(".docx"):
        raise ValidationError(u'Please attach pdf or docx file only')"""


class JoinForm(forms.Form):
    def __init__(self, *args, **kwargs):
       MAJORS = (("Management Information System", "Management Information System"),
                 ("Operation & Supply Chain Management", "Operation & Supply Chain Management"),
                 ("Marketing", "Marketing"),
                 ("Economics", "Economics"),
                 ("Management", "Management"),
                 ("Accounting", "Accounting"),
                 ("Public Administration", "Public Administration"),
                 ("Finance", "Finance"))
       super(JoinForm, self).__init__(*args, **kwargs)
       self.fields['major'] = forms.ChoiceField(
           choices=MAJORS )
    name = forms.CharField(label='Name', max_length=50)

    gpa = forms.FloatField(label="GPA")
    mgpa = forms.FloatField(label="Major GPA")
    passed_credit = forms.IntegerField(label="Passed Credit")
    graduation_course = forms.CharField(label="Expected graduation semester", max_length=50)
    phone_number = forms.IntegerField(label="Phone Number")
    email = forms.EmailField(label="Email")

club/views.py
from events.models import Event
from django.shortcuts import render, redirect,render_to_response
from django.conf import settings
from django.core.mail import EmailMessage
from django.contrib import messages
from .forms import JoinForm
from .models import Picture, Member, Video, Category, WelcomingWord, HomePageVideo,ContactUsVideo
from .models import FAQ as FAQModel
from club.instagram_api_reader import InstagramReader
from django.views.static import serve
from django.template import RequestContext

import os


def join_us(request):
    ''' This function will get the uploaded file and send it to
    Qmis club email with the name of the sender and the application attached
    '''
    if request.method == 'POST':
        form = JoinForm(request.POST)
        if form.is_valid():
            email = EmailMessage(
                'Join request from {}'.format(form.cleaned_data['name']),
                """Name: {}
Major: {}
GPA: {}
Major GPA: {}
Passed Credit: {}
Expected graduation date: {}
Phone Number: {}
Email: {}""".format(form.cleaned_data['name'], form.cleaned_data['major'], form.cleaned_data["gpa"], form.cleaned_data[
                    "mgpa"], form.cleaned_data["passed_credit"], form.cleaned_data["graduation_course"], form.cleaned_data["phone_number"], form.cleaned_data["email"]),

                to=['qmisclub_ku@hotmail.com'])
            email.send()
            messages.success(request, 'Your application has been submitted')
            return redirect('index')
    else:
        form = JoinForm()
    return render(request, 'join_us.html', {'form': form})


def view_about_us(request):
    '''This function will get all the members from member model and
    order the ascendingly by rank and view them in about us html'''
    obj = Member.objects.all().order_by('rank')
    return render(request, 'about_us.html', {'members': obj})


def index(request):
    ''' This function will get all the objects in Picture model and send them to
            html template to display in the gallery slideshow'''
    #obj = Picture.objects.filter(home_page=True)
    events = Event.objects.all()
    welcoming_word = WelcomingWord.objects.all()
    home_page_video = HomePageVideo.objects.all()
    insta_reader = InstagramReader()
    insta_imgs = insta_reader.get_last_media(num_images=5)
    return render(request, 'index.html', {'events': events, 'instagram': insta_imgs, 'welcoming_word': welcoming_word, 'home_page_video': home_page_video})


def FAQ(request):
    ''' This function will get all the objects in FAQ model and send them to
            html template '''
    objs = FAQModel.objects.all()

    return render(request, 'FAQ.html', {'objs': objs})


def gallery(request):
    ''' This function will get all the objects in Picture model and send them to
            html template to display in the gallery portfolio'''
    obj = Picture.objects.all().order_by('-pk')
    categories = Picture.objects.values(
        'category__name').distinct().order_by('category__name')
    return render(request, 'gallery.html', {'images': obj, 'categories': categories})


def useful_videos(request):
    ''' This function will get all the objects in videos model and send them to
            html template to display in the videos portfolio'''
    obj = Video.objects.all().order_by('category')
    categories = Video.objects.values(
        'category__name').distinct().order_by('category__name')

    return render(request, 'useful_videos.html', {'videos': obj, 'categories': categories})


def member_profile(request, member_id):
    '''This funtion will get specific member profile and display it.'''
    obj = Member.objects.get(pk=member_id)
    return render(request, 'member_profile.html', {'member': obj})

def contact_us(request):
    '''This function will get contact us video'''
    obj = ContactUsVideo.objects.all()
    return render(request, 'contact_us.html',{'video':obj})



def handler404(request):
    response = render_to_response('404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler500(request):
    response = render_to_response('404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 500
    return response

club/templates/FAQ.html
{% extends "base.html"%} {% block content %}
<title>
    {%block title%} FAQ {%endblock%}
</title>
<div class="container">
    {% for obj in objs %}{% if forloop.counter == 1 %}
    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr>
                <h2 class="text-center">FAQ</h2>
                <hr>
                <h3>Q: {{obj.question}}</h3>
                <p>A: {{obj.answer}}</p>
            </div>
        </div>
    </div>
    {% else %}
    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <h3>Q: {{obj.question}}</h3>
                <p>A: {{obj.answer}}</p>
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>
{%endblock%}

club/templates/about_us.html
{% extends "base.html"%} {% block content %} {% load staticfiles%}
<title>
    {%block title%} About Us {%endblock%}
</title>
<div class="container">
    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr>
                <h1 class="intro-text text-center">About
                  <strong>Us</strong>
              </h1>
                <hr>
            </div>
            <div class="col-lg-12">

              </div>
        </div>
    </div>
    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <h2 class="intro-text text-center"> Mission </h2>
                <p> <b>Awareness:</b> Increase awareness about MIS and OSCM majors through organizing information sessions, hosting guest speakers, and providing orientation programs about the majors, as well as additional information about professional certifications
                    and careers.
                </P>
                <p> <b>Skills development:</b> Provide training programs and seminars to develop technical skills (IT skills, analytics, quantitative) and professional skills (formal writing, presentation skills, etc.) of CBA students that are within the
                    scope of MIS and OSCM careers.</p>
                <p> <b>Creating collegial environment:</b> Promote a positive academic environment that motivates student participation in extracurricular activities, encourage collaboration, alleviate student stress and enforce high ethical values. </p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="box">
            <div class="col-lg-12">
                <hr>
                <h1 class="intro-text text-center">Our
                    <strong>Members</strong>
                </h1>
                <hr>
            </div>
            {% for member in members %}
            <div class="col-sm-4 text-center">
                {% if member.picture %}
                <a href="{% url 'member_profile' member.pk %}"><img class="img-circle img-responsive" src="{{member.picture.url}}" alt="" height="450" width="750"></a> {% else %}
                <a href="{% url 'member_profile' member.pk %}"><img class="img-circle img-responsive" src="{% static 'img/default-profile-picture.png'%}" alt="" height="450" width="750"> </a>{% endif %}
                <h2><a href="{% url 'member_profile' member.pk %}" style="color:black">{{member.name}}</a>
                    <br>
                    <small>{{member.position}}</small>
                </h2>
            </div>
            {% if forloop.counter|divisibleby:"3" and not forloop.first%}

            <div class="row"></div>

            {% endif %} {% endfor %}
            <div class="clearfix"></div>
        </div>
    </div>
</div>
{%endblock%}

club/templates/contact_us.html
{% extends "base.html"%} {% block content %} {% load staticfiles %}
<style>
    p {
        word-wrap: break-word;
        padding-right: 5px
    }
</style>
<title>
    {%block title%} Contact Us {%endblock%}
</title>
<link href="{% static 'css/main.css' %}" rel="stylesheet">
<link href="{% static 'css/business-casual.css' %}" rel="stylesheet">

<section id="contact-info">
    <div class="container">
        <div class="row">
            <div class="box">
                <div class="center">
                    <hr>
                    <h2 class="intro-text text-center">Contact
                      <strong>Us</strong>
                  </h2>
                    <hr>

                    <p class="lead">We’re Glad to Help!<br>
Have any questions, suggestions or complaints? Feel free to share it with us at any time and we’ll reply to you as soon as possible.</p>
                </div>
                <div class="gmap-area">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-7 col-sm-7 col-xs-12 text-center">
                                <div class="map-responsive">
                                    <iframe frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3477.963195987444!2d47.91530914989208!3d29.34207435827723!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3fcf8ff6ba279b79%3A0x8534b858393cd536!2sCollege+of+Business+Administration!5e0!3m2!1sen!2skw!4v1486313169921"
                                       allowfullscreen></iframe>
                                </div>
                            </div>
                            <div class="col-sm-5 col-xs-12 map-content" style="margin-top: 5px">
                                <ul class="row">
                                    <li class="col-sm-12">
                                        <address>
                                <h4><b>QMIS Club</b></h4>
                                <p>Twitter: @qmisclub_ku</p>
                                <p>Email: qmisclub_ku@hotmail.com</p>
                            </address>

                                        <address>
                                <h4><b>Developers</b></h4>
                                <p>Email: <ul style="margin-left: 20px">
                                            <li>
                                            abdullatifalzaidan@gmail.com (Abdullatif Al-Zaidan, Project Manager)
                                          </li>
                                          <li>
                                          yousefmon@gmail.com (Yousef Al-Ghanim, Programmer)
                                        </li>
                                        <li>
                                          nsoulper@gmail.com (Mohammed Albarrak, Programmer)
                                        </li>
                                        </ul>
                                          </p>
                                <p>Email: qmiswebsiteteam@gmail.com</p>
                            </address>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-7 col-sm-7 col-xs-12" style="padding-bottom: 10px">
                  <div class="embed-responsive embed-responsive-16by9">
                      <iframe   src="https://www.youtube.com/embed/{% for vid in video %}{{vid.video_id}}{% endfor %}?controls=2&rel=0" frameborder="0" allowfullscreen></iframe>
                  </div>
                </div>
                <div class="col-lg-5 col-sm-5 col-xs-12">
                    <a class="twitter-timeline" data-dnt="true" data-width="100%" data-height="350" href="https://twitter.com/QMISCLUB_KU">Tweets by QMISCLUB_KU</a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</section>
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
{% block jquery %}<script id="twitter-wjs" type="text/javascript" async defer src="//platform.twitter.com/widgets.js"></script>{% endblock %}
 {%endblock%}

club/templates/gallery.html
{%extends 'base.html'%}{%block content%} {% load staticfiles %}{% load social_widgets %}
<title>
    {%block title%} Gallery {%endblock%}
</title>
<link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
<link href="{% static 'css/animate.min.css' %}" rel="stylesheet">
<link href="{% static 'css/main.css' %}" rel="stylesheet">
<link href="{% static 'css/business-casual.css' %}" rel="stylesheet">


<section id="portfolio">
    <div class="container">
      <div class="box">
        <hr>
        <h2 class="intro-text text-center">Gallery</h2>
        <hr>


        <ul class="portfolio-filter text-center">
            <li style="padding-bottom:10px"><a class="btn btn-default active" href="#" data-filter="*">All</a></li>
            {% for category in categories %}
            {% for key, value in category.items %} {% if value%}
            <li style="padding-bottom:10px"><a class="btn btn-default" href="#" data-filter=".{{value|cut:" "|cut:"."|cut:":"|cut:","}}">{{value}}</a></li>

            {% endif %}{% endfor %}{% endfor %}
        </ul>
        <!--/#portfolio-filter-->

        <div class="row">
            <div class="portfolio-items">
              {% for image in images %}

                <div class="portfolio-item {{image.category|cut:" "|cut:"."|cut:":"|cut:","}} apps col-xs-12 col-sm-4 col-md-3">
                    <div class="recent-work-wrap">
                      <a class="hidden-sm-down" href="{{image.image.url}}" rel="prettyPhoto">
                        <img class="img-responsive-center" src="{{image.thumbnail.url}}" alt="" style="margin-bottom:10px">
                        </a>
                        <img class="hidden-md-up img-responsive-center" src="{{image.image.url}}" alt="" style="margin-bottom:10px">
                            <div class="recent-work-inner">
                            </div>
                                </a>
                    </div>
                </div>

                {% endfor %}
            </div>
        </div>
    </div>
</section>
<!--/#portfolio-items-->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
{%endblock%}
{% block jquery %}
<script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
<script src="{% static 'js/jquery.isotope.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script id="twitter-wjs" type="text/javascript" async defer src="//platform.twitter.com/widgets.js"></script>
{%endblock%}

club/templates/join_us.html
{% extends "base.html" %} {% block content %} {% load staticfiles %}
<link href="{% static 'css/join_us.css' %}" rel="stylesheet">
<title>
    {%block title%} Join Us {%endblock%}
</title>
<div class="container">
    <div class="row">
        <div class="box">
            <div class="col-lg-12 text-center">
                <div class="text-center">
                    <hr>
                    <h2 class="intro-text text-center">Join
                <strong>Application</strong>
            </h2>
                    <hr>
                    <form action="{% url 'join_us' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label for="text" class="col-sm-4 col-form-label text-right">{{form.name.label}}: </label>
                            <div class="col-sm-4">
                                <input type="text" name="name" id="id_name" class="form-control" placeholder="Please enter your name" style="margin-bottom:5px" required />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label text-right">{{form.major.label}}:</label>
                            <div class="col-sm-4  selectContainer">
                                <select class="form-control" name="major" id="id_major">
                              <option value="">Choose your major</option>
                                      <option value="Accounting">Accounting</option>
                                      <option value="Economics">Economics</option>
                                      <option value="Finance">Finance</option>
                                      <option value="Management">Management</option>
                                      <option value="Management Information System">Management Information System</option>
                                      <option value="Marketing">Marketing</option>
                                      <option value="Operation & Supply Chain Management">Operation & Supply Chain Management</option>
                                      <option value="Public Administration">Public Administration</option>
                                    </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="text" class="col-sm-4 col-form-label text-right">{{form.gpa.label}}: </label>
                            <div class="col-sm-4">
                                <input type="text" name="gpa" id="id_gpa" class="form-control" placeholder="Please enter your GPA" style="margin-bottom:5px" required />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="text" class="col-sm-4 col-form-label text-right">{{form.mgpa.label}}: </label>
                            <div class="col-sm-4">
                                <input type="text" name="mgpa" id="id_mgpa" class="form-control" placeholder="Please enter your Major GPA" style="margin-bottom:5px" required />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="text" class="col-sm-4 col-form-label text-right">{{form.passed_credit.label}}: </label>
                            <div class="col-sm-4">
                                <input type="text" name="passed_credit" id="id_passed_credit" class="form-control" placeholder="Please enter your Passed Credit" style="margin-bottom:5px" required />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="text" class="col-sm-4 col-form-label text-right">{{form.graduation_course.label}}: </label>
                            <div class="col-sm-4">
                                <input type="text" name="graduation_course" id="id_graduation_course" class="form-control" placeholder="Spring 2018" style="margin-bottom:5px" required />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="text" class="col-sm-4 col-form-label text-right">{{form.phone_number.label}}: </label>
                            <div class="col-sm-4">
                                <input type="text" name="phone_number" id="id_phone_number" class="form-control" placeholder="Please enter your phone number" style="margin-bottom:5px" required />
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="text" class="col-sm-4 col-form-label text-right">{{form.email.label}}: </label>
                            <div class="col-sm-4">
                                <input type="text" name="email" id="id_email" class="form-control" placeholder="Please enter your email" style="margin-bottom:5px" required />
                            </div>
                        </div>
                        <div class="row"></div>
                        {% if form.errors %}
                        <div class="alert alert-error">
                            <button type="button" class="close" data-dismiss="alert">×</button> {% for field in form %} {% if field.errors %}
                            <li>{{ field.label }}: {{ field.errors|striptags }}</li>
                            {% endif %} {% endfor %}
                        </div>
                        {% endif %}
                        <input class="btn btn-danger btn-danger" type="submit" value="Submit">

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %} {% block jquery %} {% endblock %}

club/templates/member_profile.html
{% extends "base.html"%} {% block content %} {% load staticfiles%}
<title>
    {%block title%} {{member.name}} {%endblock%}
</title>
<div class="container">
    <div class="row">

        <div class="col-sm-12">
            <div class="box">
                <hr>
                <h1 class="intro-text text-center">{{member.name}}

              </h1>
                <hr>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="box">
                <div class="col-sm-4 text-center">
                    {% if member.picture %}
                    <img class="img-circle img-responsive" src="{{member.picture.url}}" alt="" height="450" width="750"> {% else %}
                    <img class="img-circle img-responsive" src="{% static 'img/default-profile-picture.png'%}" alt="" height="450" width="750"> {% endif %}
                </div>
                <div class="col-sm-8 text-left">
                    <br>
                    <br>
                    <br>
                    <br>
                    <P> <b> Major:</b> {{ member.major}}</p>
                    <P> <b> Skills:</b> {{ member.skills}}</p>
                    <P> <b> Interests:</b> {{ member.interests}}</p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}